### PR TITLE
Address metadata during altexp merging and other metadata fixes

### LINKED ISSUE #250: Fix merging metadata bug
I'm pretty sure we have a bug in how we handle merging SCE metadata, such that we may have accidentally ended up with a lot of duplicate items. I have not dug into this much, but noticed that something looked funky. 

This issue therefore encompasses formally diagnosing the bug, and then fixing it.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #250 

This (surprise!) PR deals with the metadata situation. To be frank, I did not formally diagnose whatever bug I thought might have been going on in #250 (indeed, there may have been no bug at all...), but I did get everything working as it should be which more or less is the goal anyways! 

This was definitely necessary because, while writing tests for #150, I realized we had yet to _fully_ deal with altExp metadata in the first place, and this itself was distracting me while writing said tests. So, I went ahead and tackled the metadata situation now via a bit of code refactoring. IMO, this makes our code much more streamlined and modular, and much easier to follow (for me, at least..) compared to what it was before.
 
This PR consolidates metadata preparation code as follows:

- At the top of `merge_sce_list()`, I check that the expected metadata fields are present. This is handled by the new function `check_metadata()`.
- After merging, I update the previous metadata into the correct merged format and add it into the merged SCE. This is handled by the new function `prepare_merged_metadata()` - this function now handles every aspect of the metadata, which again I think greatly simplifies the script overall and makes it easier to follow.
  - For any altExps that didn't exist and were create on the fly with `combineCols`, I also create a "MVM" (minimum viable metadata) list to include in the final merged object with `extract_metadata_for_altexp()`. All other potential metadata fields will therefore end up get filled in with `NULL`.
    - Note that  `extract_metadata_for_altexp()` could also be an anonymous function in the `purrr::map()` directly?
    - Note also that `prepare_merged_metadata()` takes a metadata list rather than SCE so that we can use it in situations where there is no metadata, ala for an altexp that didn't originally exist

All is tested and passing locally. Enjoy today's🎢 !

### CODE REVIEW

**Comment by sjspielman** [comment]
Noting I'm going to wait to request review here until #251 is merged.

**Review by jashapiro — COMMENTED** [review]
Much of this looks good, but I think you made a pretty big change to the contents of `library_metadata` in that you are now returning the transposed data. I think we want to leave it as it was, with contents organized first by the SCE name, such that `metadata(merged_sce)$library_metadata[["sce1"]]` returns the original metadata as it went in for each SCE.

Note that you may not want to just re-transpose, as that will add in `NULL` values for any metadata fields that are not present in all samples.

I had a few other comments below, but I think most of those are more minor, except maybe for the one about preserving order in the altExp metadata.

**Comment by sjspielman** [comment]
Noting the GHA error - 

```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorstore==0.1.36 from https://files.pythonhosted.org/packages/0c/7e/ec209ed096cc55b10e4d25a84f6683b8916d4808fa0f92881e24de5a30bb/tensorstore-0.1.36-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from -r /tmp/Rtmp6pk8WG/renv-requirements-14d51b25703a.txt (line 131)):
        Expected sha256 d50b27919cde623e3918fe6ba054f41e2da5d7dbf7817d46d43131b50bcc9df4
             Got        0e5e398e0345ef50eae04967b739f9517b534c5d5a3250d402bfbd451c35a045
```

File: R/merge_sce_list.R [hunk 1]
```diff
@@ -102,6 +105,17 @@ merge_sce_list <- function(
...
     retain_coldata_cols <- c(retain_coldata_cols, altexp_columns)
+
+    # Check each altExp metadata, for SCEs with the altExp
+    names(altexp_attributes) |>
+      purrr::walk(
+        \(altexp_name) {
+          sce_list |>
+            purrr::keep(\(sce) altexp_name %in% altExpNames(sce)) |>
+            purrr::map(altExp, altexp_name) |>
+            check_metadata()
```
[the remark this answers is not in the document]
Comment (sjspielman) [reply R/merge_sce_list.R:116]: Yeah, I agree it could sort of go either way. I figure if someone wanted to fully pull out the altexp it might be useful to have this information handy?

**Comment by jashapiro** [comment]
> Noting the GHA error -

This can be safely ignored as a transient cache problem, unless we start to see it on every build. `renv` does not store the caches in the requirements file.

**Comment by sjspielman** [comment]
Passing locally! ✅

File: R/merge_sce_list.R [hunk 2]
```diff
@@ -219,8 +184,29 @@ merge_sce_list <- function(
...
+        purrr::keep(\(sce) !(altexp_name %in% altExpNames(sce))) |>
+        purrr::map(extract_metadata_for_altexp)
+
+      # Update metadata in altExps that were originally present
+      metadata_list <- sce_list |>
+        purrr::keep(\(sce) altexp_name %in% altExpNames(sce)) |>
+        purrr::map(altExp, altexp_name) |>
+        purrr::map(metadata) |>
+        # Tack on the metadata we created on the fly
+        c(additional_metadata)
```
[the remark this answers is not in the document]
Comment (sjspielman) [reply R/merge_sce_list.R:205]: https://github.com/AlexsLemonade/scpcaTools/pull/255/commits/c26d82621dc767d5ff0e696bc1b64fc52762eb89

File: R/merge_sce_list.R [hunk 3]
```diff
@@ -445,3 +398,125 @@ get_altexp_attributes <- function(sce_list) {
...
+      "This SCE object appears to be a merged object",
+      "We do not support merging objects with objects that have already been merged."
+    ))
+  }
+
+  # Create new version of metadata_list without any sample_metadata fields
+  # Note that this will work even if `sample_metadata` is not present
+  library_metadata <- metadata_list |>
+    purrr::map(
+      \(meta) purrr::assign_in(meta, "sample_metadata", purrr::zap())
```
Comment (sjspielman) [inline R/merge_sce_list.R:448]: ⚡

File: tests/testthat/test-merge_sce_list.R [hunk 4]
```diff
@@ -580,3 +606,81 @@ test_that("get_altexp_attributes throws an error as expected when features do no
...
+    observed_metadata$sample_id,
+    glue::glue("sample-{names(sce_list)}")
+  )
+  expect_setequal(
+    observed_metadata$library_metadata |>
+      purrr::map(names) |>
+      purrr::reduce(intersect),
+    c("library_id", "sample_id", "mapped_reads", "ambient_profile")
+  )
+})
```
Comment (jashapiro) [inline tests/testthat/test-merge_sce_list.R:686]: I think these tests are probably redundant. You already do much of the required testing for altExp metadata in the tests for the full merge with altExps, so this is really just repeating the `prepare_merged_metadata()` tests with a slightly different set of data. But it is good that you are testing that the behavior is correct when `sample_metadata` doesn't exist, so I guess maybe leave it!

File: tests/testthat/test-merge_sce_list.R [hunk 5]
```diff
@@ -526,15 +500,67 @@ test_that("merging SCEs where 1 altExp is missing works as expected, with altexp
...
+    glue::glue("library-{names(sce_list_with_altexp)}")
+  )
+  expect_setequal(
+    altexp_metadata$sample_id,
+    glue::glue("sample-{names(sce_list_with_altexp)}")
+  )
+
+
+  expect_setequal(
+    # all but sce4
```
Comment (jashapiro) [inline tests/testthat/test-merge_sce_list.R:520]:
```suggestion
    # all but sce4 contain all metadata components
```

File: tests/testthat/test-merge_sce_list.R [hunk 6]
```diff
@@ -526,15 +500,67 @@ test_that("merging SCEs where 1 altExp is missing works as expected, with altexp
...
+    altexp_metadata$library_metadata[-4] |>
+      purrr::map(names) |>
+      purrr::reduce(intersect),
+    c("library_id", "sample_id", "mapped_reads", "ambient_profile")
+  )
+
+  expect_setequal(
+    # only sce4
```
Comment (jashapiro) [inline tests/testthat/test-merge_sce_list.R:528]:
```suggestion
    # sce4 has only library id and sample id, as it was missing the altExp
```

**Review by jashapiro — COMMENTED** [review]
Okay, a bunch of small comments, but I think we are almost there. 

The biggest thing is probably just adding a few tests that we get the `sample_metadata` table correct when we merge the metadata. We do check it as part of the main merge checks, a bit, but it would be good to have those tests in the `prepare_merged_metadata` tests as well.

File: tests/testthat/test-merge_sce_list.R (hunk 4 above)
Comment (sjspielman) [reply tests/testthat/test-merge_sce_list.R:686]: I had almost the identical thought process about redundancy and then deciding maybe it was ok!

File: tests/testthat/test-merge_sce_list.R [hunk 7]
```diff
@@ -580,3 +606,81 @@ test_that("get_altexp_attributes throws an error as expected when features do no
...
+  observed_list <- extract_metadata_for_altexp(sce_list[[1]])
+  expect_equal(
+    names(observed_list), names(expected_list)
+  )
+  expect_equal(
+    unlist(observed_list), unlist(expected_list)
+  )
+})
+
+test_that("prepare_merged_metadata works as expected, with sample_metadata present", {
```
[the remark this answers is not in the document]
Comment (sjspielman) [reply tests/testthat/test-merge_sce_list.R:626]: https://github.com/AlexsLemonade/scpcaTools/pull/255/commits/3598c946d05598296c7471b24acbac51618b7d96

File: R/merge_sce_list.R [hunk 8]
```diff
@@ -219,8 +184,32 @@ merge_sce_list <- function(
...
+  # Update metadata in merged objects, using the unmerged sce_list
+  metadata(merged_sce) <- sce_list |>
+    purrr::map(metadata) |>
+    prepare_merged_metadata()
+
+  if (include_altexp) {
+    for (altexp_name in names(altexp_attributes)) {
+      # For any SCEs without this altExp, create the library_id and sample_id metadata
+      additional_metadata <- sce_list |>
+        purrr::keep(\(sce) !(altexp_name %in% altExpNames(sce))) |>
```
[the remark this answers is not in the document]
Comment (sjspielman) [reply R/merge_sce_list.R]: https://github.com/AlexsLemonade/scpcaTools/pull/255/commits/24e97b1af7eddb36676dadabd027c9190be8647d

File: R/merge_sce_list.R (hunk 3 above)
Comment (jashapiro) [reply R/merge_sce_list.R:446]: I thought I commented about this, but maybe I didn't. what you have here obviously works, but I feel like it is a bit... over-engineered? I'd do a more direct manipulation:

```suggestion
      \(meta) meta[which(names(meta) != "sample_metadata")]
```
(using `which` to be safe)

Comment (sjspielman) [reply R/merge_sce_list.R:446]: > over-engineered

What a nice euphemism for me! 😂

File: R/merge_sce_list.R [hunk 9]
```diff
@@ -219,8 +184,35 @@ merge_sce_list <- function(
...
+      has_altexp_name <- sce_list |>
+        purrr::map_lgl(\(sce) (altexp_name %in% altExpNames(sce)))
+
+      # For any SCEs without this altExp, create the library_id and sample_id metadata
+      additional_metadata <- sce_list |>
+        purrr::discard(has_altexp_name) |>
+        purrr::map(extract_metadata_for_altexp)
+
+      # Update metadata in altExps that were originally present
+      metadata_list <- sce_list |>
```
Comment (jashapiro) [inline R/merge_sce_list.R:203]: Just because I keep getting confused in this section about which metadata we are dealing with
```suggestion
      altexp_metadata_list <- sce_list |>
```

File: R/merge_sce_list.R [hunk 10]
```diff
@@ -219,8 +184,35 @@ merge_sce_list <- function(
...
+        purrr::keep(has_altexp_name) |>
+        purrr::map(altExp, altexp_name) |>
+        purrr::map(metadata) |>
+        # Tack on the metadata we created for libraries without altExps
+        c(additional_metadata)
+
+      # Ensure correct order
+      metadata_list <- metadata_list[names(sce_list)]
+
+      metadata(altExp(merged_sce, altexp_name)) <- prepare_merged_metadata(metadata_list)
```
Comment (jashapiro) [inline R/merge_sce_list.R:213]:
```suggestion
      altexp_metadata_list <- metadata_list[names(sce_list)]

      metadata(altExp(merged_sce, altexp_name)) <- prepare_merged_metadata(altexp_metadata_list)
```

**Review by jashapiro — APPROVED** [review]
I made one small variable name suggestion, but I think this should be good to go.

File: R/merge_sce_list.R [hunk 11]
```diff
@@ -219,8 +184,35 @@ merge_sce_list <- function(
...
+      # Update metadata in altExps that were originally present
+      altexp_metadata_list <- sce_list |>
+        purrr::keep(has_altexp_name) |>
+        purrr::map(altExp, altexp_name) |>
+        purrr::map(metadata) |>
+        # Tack on the metadata we created for libraries without altExps
+        c(additional_metadata)
+
+      # Ensure correct order
+      altexp_metadata_list <- metadata_list[names(sce_list)]
```
Comment (jashapiro) [inline R/merge_sce_list.R:211]:
```suggestion
      altexp_metadata_list <- altexp_metadata_list[names(sce_list)]
```
